# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='card',
            name='health',
        ),
        migrations.RemoveField(
            model_name='card',
            name='special',
        ),
    ]
