# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hearthstone', '0003_minion_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='className',
            field=models.CharField(default='Neutral', max_length=30),
        ),
    ]
