# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hearthstone', '0004_card_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card',
        ),
        migrations.AddField(
            model_name='deck',
            name='deckClass',
            field=models.CharField(max_length=20, null=True, validators=['Rogue', 'Mage', 'Druid', 'Warrior', 'Priest', 'Paladin', 'Warlock', 'Shaman', 'Hunter']),
        ),
        migrations.AddField(
            model_name='deck',
            name='minions',
            field=models.ManyToManyField(to='Hearthstone.Minion'),
        ),
        migrations.AddField(
            model_name='deck',
            name='spells',
            field=models.ManyToManyField(to='Hearthstone.Spell'),
        ),
        migrations.AlterField(
            model_name='card',
            name='className',
            field=models.CharField(default='Neutral', max_length=30, validators=['Rogue', 'Mage', 'Druid', 'Warrior', 'Priest', 'Paladin', 'Warlock', 'Shaman', 'Hunter', 'Neutral']),
        ),
    ]
