# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hearthstone', '0005_auto_20170802_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
