# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hearthstone', '0006_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='minion',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hearthstone.Spell'),
        ),
    ]
